### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by masudr4n4** [grimmer0125/Kiteretsu#3]
Hallo 
I am Md Masud Rana 
Great to know about this projects but this projects have no logo.I am a graphics designer wants to make a logo for this projects.Its totally free for open source projects.
Thank you

**Comment by grimmerk** [comment]
Hi Md Masud Rana, 

Thank you. I have updated the wiki to introduce the current implemented features and show some screenshots. The main functions of the 1st stage are roughly finished. I plan to submit this project to apple app store and Google play store. I hope everything will be OK. Before that, a logo and possible better UI should benefit this project a lot. 

Actually, I'm also looking for some graphic designers' help locally and not sure if I can get one or not. I very welcome any contribution and very happy someone wanna to help. If you do not mind some possible situation (e.g. not match my visual preference....), making a logo is OK (upload somewhere or making a GitHub PR) and we can see the results and discuss if adapting it or not. 

Again, I appreciate your enthusiasm very much. 

By the way, I'm not familiar with the assets standard of React Native and will check it recently. I guess it is the same as the spec of iOS's logo design and Android's.

**Comment by grimmerk** [comment]
I'm going to close this since I have applied some logos from a free website
